# Math Primer for AI

본 페이지는 한림대학교 딥러닝이해및활용(710231) 수업에서 학생들의 Python 학습을 위해 만든 페이지입니다.
2020/09/01

In [ ]:
import numpy as np

## Matrix multiplication

In [ ]:
a = np.array([[1, -3, 2], [4, 0, -5]])
print(a)

[[ 1 -3  2]
 [ 4  0 -5]]


In [ ]:
a.shape

(2, 3)

In [ ]:
b = np.array([[3], [1], [2]])
print(b)

[[3]
 [1]
 [2]]


In [ ]:
b.shape

(3, 1)

In [ ]:
c = np.matmul(a, b) #matrix multiplication
print(c)
#print(c.shape)

[[4]
 [2]]


In [ ]:
d = np.dot(a, b)
print(d)

[[4]
 [2]]


위 둘의 결과 (matmul, dot) 가 어떤가요? 확인해보세요

아래처럼 shape을 출력해보는 습관을 가지세요

In [ ]:
d.shape

(2, 1)